run:
	python3 manage.py runserver 0.0.0.0:6999

makemigrations:
	python3 manage.py makemigrations

migrate:
	python3 manage.py migrate

superuser:
	python3 manage.py createsuperuser

.PHONY: run makemigrations migrate
