# Generated by Django 4.0.2 on 2022-02-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DavidsShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingAddress1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingAddress2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingAddressZip',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingCountry',
            field=models.TextField(default=''),
        ),
    ]
